trees_everywhere/core/urls.py
from django.urls import path
from .views import *
from .viewsets import *

urlpatterns = [
    # User
    path('login/', user_login, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register, name='register'),
    path('users_list/', users_list, name='users_list'),
    path('delete_user/<int:id>/', delete_user, name='delete_user'),
    # account
    path('create_account/', create_account, name='create_account'),
    path('account_list/', account_list, name='account_list'),
    path('account_detail/<int:id>/', account_detail, name='account_detail'),
    path('account_delete/<int:id>/', account_delete, name='account_delete'),
    path('edit_account/<int:id>/', edit_account, name='edit_account'),
    path('update_status/<int:id>/', update_status, name='update_status'),
    path('ajax_change_account/', change_account, name='change_account'),
    # Profile
    
    path('profile/', profile, name='profile'),
    path('edit_profile/<int:id>/', edit_profile, name='edit_profile'),

    # Tree
    path('home/', home , name='home'),
    path('trees/', user_trees, name='user_trees'),
    path('edit_tree/<int:id>/', edit_tree, name='edit_tree'),
    path('tree_detail/<int:pk>/', tree_detail, name='tree_detail'),
    path('add_plant/', add_plant, name='add_plant'),
    path('add_tree/', add_tree, name='add_tree'),
    path('delete_tree/<int:id>/', delete_tree, name='delete_tree'),

    # API METHODS
    path('api/v1/trees/', UserPlantedTreesList.as_view(), name='user_planted_trees_api'),
]

trees_everywhere/trees_everywhere/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", user_login, name='login'),
    path('', include('core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

trees_everywhere/core/models.py
from django.db import  models
from django.contrib.auth.models import User


class CustomUser(User):
    def print(self):
        return print('oi')
 
    def plant_tree(self, plant, location, account):
        planted_tree = PlantedTree.objects.create(user=self, plant=plant, latitude=location[0], longiture=location[1], account=account)
        return planted_tree
        
    
    def plant_trees(self, plantings, account):
        for plant, location in plantings:
            self.plant_tree(plant, location, account)

    
    def get_profile(self,):
       
        profile = Profile.objects.filter(user=self)
        if profile.count():
            return profile.first()
        return None
              

         

class Account(models.Model):
    name = models.CharField(max_length=255)
    active = models.BooleanField(default=True)
    users = models.ManyToManyField(CustomUser, related_name='accounts')

    def __str__(self):
        return self.name

class Profile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    bio = models.TextField(null=True, blank=True, default='')
    joined_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.user.username

class Plant(models.Model):
    name = models.CharField(max_length=255)
    scientific_name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class PlantedTree(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)
    latitude = models.DecimalField(max_digits=9, decimal_places=6)
    longiture = models.DecimalField(max_digits=9, decimal_places=6)
    planted_at = models.DateTimeField(auto_now_add=True)
    age = models.IntegerField(default=0)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.plant.name} plantada por {self.user.username}'
    
    def location(self):
        return (self.latitude, self.latitude)

trees_everywhere/core/forms.py
from .models import *
from django import forms
from django.contrib.auth.forms import AuthenticationForm ,UserCreationForm
from django.contrib.auth import login, authenticate


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Digite seu username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Digite sua senha'}))
    account = forms.ModelChoiceField(queryset=Account.objects.filter(active=True).order_by('name'), 
                                     required=True, 
                                     widget=forms.Select(attrs={"class": "form-control"}))

    def __init__(self, request=None, *args, **kwargs):
        super().__init__(request, *args, **kwargs)
        
    def clean_account(self):
        data = self.cleaned_data['account']
        user = authenticate(username=self.cleaned_data.get('username'), password=self.cleaned_data.get('password'))
        if user == None:
            raise forms.ValidationError("Login ou senha invalidos.")

        for u in data.users.all():
            if u.id == user.id:
                return data

        raise forms.ValidationError("Esse Usuário não pertence a essa conta.")


  

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'first_name', 'password1', 'password2', 'account']

    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Digite o Username'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Digite o Email'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Digite o Nome'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Digite a Senha'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirme a Senha'}))
    account = forms.ModelMultipleChoiceField(queryset=Account.objects.filter(active=True).order_by('id'),
                                     
                                       widget=forms.SelectMultiple(attrs={'class': 'form-control multiselect select2 '}))
    bio = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Biografia'}))

    def __init__(self, *args, **kwargs):
        super(CustomAuthenticationForm, self).__init__(*args, *kwargs)
        self.fields['account'].initial = Account.objects.filter(active=True).first()

class AccountCreationForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['name', 'active', 'users']

    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Digite o nome da Conta'}))
    active = forms.BooleanField(initial=True, widget=forms.NullBooleanSelect(attrs={'class': 'form-control'}))
    users = forms.ModelMultipleChoiceField(queryset=CustomUser.objects.all(),
                                            widget=forms.SelectMultiple(attrs={'class': 'form-control multiselect select2'})
    )
 
    def __init__(self, *args, **kwargs):
        account = kwargs.pop('account', None)  
        super(AccountCreationForm, self).__init__(*args, **kwargs)
        self.fields['users'].widget.attrs['class'] = 'form-control'
        self.fields['users'].initial = CustomUser.objects.all().first()    

        if account:
            self.fields['name'].initial = account.name
            self.fields['active'].inital = account.active
            self.fields['users'].initial = account.users.all()
        
            
        
class PlantForm(forms.Form):
   

    name = forms.ModelChoiceField(queryset=Plant.objects.all().order_by('name'), 
                                     required=True, 
                                     widget=forms.Select(attrs={"class": "form-control"}))
    
    age = forms.IntegerField()
    latitude =  forms.DecimalField(max_digits=9, decimal_places=6)
    longiture = forms.DecimalField(max_digits=9, decimal_places=6)

    def __init__(self, *args, **kwargs):
        tree = kwargs.pop('tree', None)
        super(PlantForm, self).__init__(*args, **kwargs)

        self.fields['latitude'].widget.attrs['class'] = 'form-control '
        self.fields['longiture'].widget.attrs['class'] = 'form-control '
        self.fields['age'].widget.attrs['class'] = 'form-control'

        if tree:
            self.fields['name'].initial = tree.plant
            self.fields['latitude'].initial = tree.latitude
            self.fields['longiture'].initial = tree.longiture
            self.fields['age'].initial = tree.age


class ProfileForm(forms.Form):
    
    username = forms.CharField( required=False,widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Digite o Username'}))
    email = forms.EmailField(required=False, widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Digite o Email'}))
    first_name = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Digite o Nome'}))
    bio = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Biografia'}))
    accounts = forms.ModelMultipleChoiceField(queryset=Account.objects.filter(active=True).order_by('id'),
                                     
                                       widget=forms.SelectMultiple(attrs={'class': 'form-control multiselect select2 '}))
    
    

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(ProfileForm, self).__init__(*args, **kwargs)

        self.fields['accounts'].initial = Account.objects.filter(active=True).first()
        if user:
            self.fields['username'].initial = user.username
            self.fields['email'].initial = user.email
            self.fields['first_name'].initial = user.first_name
            profile = user.get_profile()
            self.fields['accounts'].initial = user.accounts.all()
            if profile:
                self.fields['bio'].initial = profile.bio

    

trees_everywhere/core/templates/403_template.html
{% extends 'base_clean.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="text-center">
        <h2 class="">403 Forbidden</h2>
        <p >Parece que você não tem permissao pra acessar essa pagina </p>
        <p><a style="font-weight: 700; font-size: 25px;" href="{% url 'home' %}"> <i class='bx bx-arrow-back bx-sm bx-tada bx-rotate-180' ></i> VOLTAR PARA HOME</a></p>
        <img class="img-fluid" style="border-radius: 30px; margin-bottom: 50px; max-height: 500px ;" src="{% static 'img/response/403.jpg'%}" alt="imagem-de-403">
    </div>
    

</div>

{% endblock %}

trees_everywhere/core/templates/add_tree.html
{% extends 'base.html' %}
{% load static %}
{% block title %} <title>Adicionar Planta</title> {% endblock %}

{% block content %}

<style>
    .btn-open-map{
        font-family: "Raleway", sans-serif;
        font-weight: 500;
        font-size: 1em;
        letter-spacing: 1px;
        display: inline-block;
        padding: 7px 16px;
        border-radius: 4px;
        transition: 0.5s;
        line-height: 1;
        color: #fff;
        animation-delay: 0.8s;
        margin: 20px 0;
        width: 100%;
        background: #5c8cb8;

    }

    #map { 
    height: 400px;
    width: 100%;
   
   }
</style>

<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-6">
          <div class="card mt-5">
              <div class="card-header text-center">
                  <h4>Adicionar Planta</h4>
              </div>
              <div class="card-body">
                  <form id="myForm" method="post"  action="{% url 'add_tree' %}">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    <div class="form-group">
                        <label for="id_plant">Planta:</label>
                        {{ form.name }}
                    </div>
                    <div class="form-group">
                        <label for="id_age">Idade:</label>
                        {{ form.age}}

                    </div>
                    <div style="margin-top: 20px;" class="form-group text-center">
                        <h5>Onde foi plantada?</h5>
                    </div>
                    
                    <div class="form-group">
                          <label for="id_latitude">Latitude:</label>
                          {{ form.latitude }}
                      </div>
                      <div class="form-group">
                          <label for="id_longiture">Longiture:</label>
                          {{ form.longiture }}
                      </div>
                      <div class="col-md-4" > 
                        <a type="button" href="#" onclick="openMap();" href="#" data-bs-toggle="modal" data-bs-target="#openMap" class="btn-open-map">Abrir mapa</a>
                      </div>
                      <button id="submit"  type="submit" class="btns-all">Salvar</button>
                  </form>
              </div>
          </div>
      </div>
  </div>
</div>


<div class="container">
    <div class="modal fade" id="openMap" tabindex="-1" aria-labelledby="openMap" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered"> <!-- Adicione a classe modal-dialog-centered -->
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="openMapLabel">Clique pra definir longitude e latitude</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              
              
                <div class="col-lg-12" id="map"></div>
               
             
            </div>
          </div>
        </div>
    </div>
    
</div>

<script>
    $("#id_name").select2({
        allowClean : true,
        placeholder: "Nome da planta",
        width: '100%'
    })

    $('#id_latitude').attr('readonly', true)
    $("#id_longiture").attr('readonly', true)

    document.addEventListener('DOMContentLoaded', function() {
            var map; 

            
            function initializeMap() {
                map = L.map('map').setView([0, 0], 2); 
                
                
                L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                    attribution: '© OpenStreetMap contributors'
                }).addTo(map);

                
                var marker;
                
                
                map.on('click', function(e) {
                    var lat = e.latlng.lat.toFixed(6);
                    var lng = e.latlng.lng.toFixed(6);
                    
                    // Atualiza os campos de latitude e longitude
                    var latInput = document.getElementById('id_latitude');
                    var lngInput = document.getElementById('id_longiture');
                    
                    if (latInput && lngInput) {
                        latInput.value = lat;
                        lngInput.value = lng;
                    }
                    
                    
                    if (marker) {
                        map.removeLayer(marker);
                    }
                    
                    
                    marker = L.marker([lat, lng]).addTo(map);

                    Swal.fire({
                            title: 'Localização Adicionada!',
                            text: 'Você adicionou a Longitude e Latitute com sucesso :)',
                            icon: 'success',
                            confirmButtonText: 'Confirmar',
                            confirmButtonColor: '#5cb874' 
                        }).then((result) => {
                            if (result.isConfirmed) {
                                console.log('deu certo')

                                var modalElement = document.getElementById('openMap');
                                var modalInstance = bootstrap.Modal.getInstance(modalElement);
                                modalInstance.hide();
                                
                            }
                        });
                });
            }

            
            var modal = document.getElementById('openMap');
            modal.addEventListener('shown.bs.modal', function () {
                if (!map) {
                    initializeMap();
                } else {
                    map.invalidateSize();
                }
            });
        });

</script>
  

{% endblock %}

trees_everywhere/core/templates/adm_account_detail.html
{% extends 'base.html' %}
{% block title %} <title>Detalhes da Conta</title> {% endblock%}

{% block content  %}

<div class="container">
  <h2 class="text-center">Detalhes da Conta </h2>
  <div class="card text-bg-light mb-3">
    <div class="card-header">{{account.name}}</div>
    <div class="card-body">
      <h5 class="card-title">{% if account.active %} Conta Ativa {% else %} Conta Inativa {% endif %}</h5>
      <p class="card-text">Lista de Usuários : {% for user in users %} {{user}},  {% endfor %}</p>
      <a href="{% url 'edit_account' account.id %}" class="btn-default-color" >Editar <i class='bx bx-edit-alt'></i></a>
      <a href="{% url 'account_delete' account.id %}" class="btn-danger-color "> Deletar <i class='bx bx-trash '></i></a>
      
    </div>
  </div>

</div>

<script>

</script>

{% endblock %}

trees_everywhere/core/templates/adm_account_list.html
{% extends 'base.html' %}
{% load static %}
{% block title%} <title>Contas</title> {% endblock %}

{% block content  %}

<div class="container">
  <div class="text-center">
    <img  class="img-fluid" width="400px" style="margin-bottom: 30px; border-radius: 20px;"  src="{% static 'img/home/account.jpg' %}" alt="home-img">
  </div>
  <div class="section-title">
    <h2 >Contas</h2>
  </div>
  

  <div class="float-right" style="max-width: 18%;" >
    <a style="font-weight: 700;" class="btns-all text-center " href="{% url 'create_account' %}" >Adicionar Conta <i class='bx bxs-plus-circle' ></i></a>
  </div>
  
  <div class="list-group">
    {% for account in accounts %}
      <div class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
        <a href="{% url 'account_detail' account.id %}" class="d-flex w-100  list-group-item-action">
          <div>
            <h5 class="mb-1">{{ account.name }}</h5>
            <small style="font-weight: 600;" class="{% if account.active %} default-color {% else %} text-danger {% endif %}">
              {% if account.active %} Conta Ativa <i class='bx bx-check'></i> {% else %} Conta Inativa <i class='bx bx-x' ></i> {% endif %}
            </small>
            <p class="mb-1">Quantidade de Usuários: {{ account.users.count }}</p>
          </div>
        </a>
        <button type="button" id="confirm-{{ account.id }}" class=" {% if account.active %} btn-danger-color {% else %} btn-default-color {% endif %}  ml-auto"> {% if account.active %} Desativar {% else %} Ativar {% endif %}</button>
      </div>
    {% endfor %}
  </div>
</div>

<script>
  {% for account in accounts %}
  document.querySelector('#confirm-{{ account.id }}').onclick = function(){
      Swal.fire({
        title: 'Status Alterado!',
        text: 'Você alterou o status dessa Conta :)',
        icon: 'success',
        confirmButtonText: 'Confirmar',
        confirmButtonColor: '#5cb874' 
      }).then((result) => {
        if (result.isConfirmed) {
            window.location.href ="{% url 'update_status' account.id %}"
        }
      });
      return false;
    }
  {% endfor %}

</script>

{% endblock %}

trees_everywhere/core/templates/adm_create_account.html
{% extends 'base.html' %}
{% block title %} <title>Criação de Conta</title> {% endblock %}
{% block content %}

<div class="container" style="margin-top: 80px; margin-bottom: 80px;">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-header text-center">
                    {% if account %}
                        <h4>Editar Conta</h4>
                    {% else %}
                        <h4>Cadastrar Conta</h4>
                    {% endif %}        

                </div>
                <div class="card-body">
                {% if account %}
                    <form method="post" action="{% url 'edit_account' account.id %}" >
                {% else %}
                    <form method="post" action="{% url 'create_account'%}">
                {% endif %}    
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        <div class="form-group">
                            <label for="id_name">Nome:</label>
                            {{ form.name }}
                        </div>
                        <div class="form-group">
                            <label for="id_active">Ativo:</label>
                            {{ form.active }}
                        </div>
                        <div class="form-group">
                            <label for="id_users">Users:</label>
                            {{ form.users }}
                        </div>
                        <button  type="submit" class="btns-all">Salvar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $("#id_users").select2({
        allowClear: true, 
        placeholder: 'Selecione um Usuario',
        width: '100%',
    })
</script>

{% endblock %}

trees_everywhere/core/templates/adm_register.html
{% extends 'base_clean.html' %}
{% block title%} <title>Cadastro</title> {% endblock %}
{% block content %}

<style>
    .smal-erros{
        color: red;
        font-size: 0.875rem;
    }
</style>

<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-6">
          <div class="card mt-5">
              <div class="card-header text-center">
                  <h4>Cadastro</h4>
              </div>
              <div class="card-body">
                <form method="post" action="{% url 'register' %}">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    <div class="form-group">
                        <label for="id_username">Username:</label>
                        {{ form.username }}
                        <div class="smal-erros">
                            {{ form.username.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_first_name">Nome:</label>
                        {{ form.first_name }}
                        <div class="smal-erros">
                            {{ form.first_name.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_email">Email:</label>
                        {{ form.email }}
                        <div class="smal-erros">
                            {{ form.email.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_password1">Senha:</label>
                        {{ form.password1 }}
                        <div class="smal-erros">
                            {{ form.password1.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_password2">Confirme a Senha:</label>
                        {{ form.password2 }}
                        <div class="smal-erros">
                            {{ form.password2.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_account">Vincular Usuario a uma Conta:</label>
                        {{ form.account }}
                        <div class="smal-erros">
                            {{ form.account.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_bio">Sobre:</label>
                        {{ form.bio }}
                        <div class="smal-erros">
                            {{ form.bio.errors }}
                        </div>
                    </div>
                    <button id="btn-register" type="submit" class="btn btn-primary">Cadastrar</button>
                </form>
            </div>
          </div>
      </div>
  </div>
</div>

<script>
    $("#id_account").select2({
        allowClear: true, 
        placeholder: 'Selecione uma Conta',
        width: '100%',
    })
</script>



{% endblock %}

trees_everywhere/core/templates/adm_users_list.html
{% extends 'base.html' %}
{% block title %} <title>Lista de Usuarios</title>{% endblock %}
{% load static %}

{% block content  %}

<div class="container">

  <div class="text-center">
    <img  class="img-fluid" width="400px" style="margin-bottom: 30px; border-radius: 20px;"  src="{% static 'img/home/earth.jpg' %}" alt="home-img">
  </div>
  <div class="section-title">
    <h2>Usuários</h2>
  </div>
  

  <div class="float-right" style="max-width: 18%;" >
    <a style="font-weight: 700;" class="btns-all text-center" href="{% url 'register' %}" >Adicionar Usuário<i class='bx bxs-plus-circle' ></i></a>
  </div>
  
  <div class="list-group">
    {% for user in users %}
      <div class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
        <a href="{% url 'profile' %}" class="d-flex w-100  list-group-item-action">
          <div>
            <h5 class="mb-1">{{ user.username}}</h5>
            <small style="font-weight: 600;" class="">
                {{user.first_name}}
            </small>
            <p class="mb-1">Email: {{ user.email }}</p>
          </div>
        </a>
        <a href="{% url 'delete_user' user.id %}" > deletar</a>
      </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

trees_everywhere/core/templates/all_trees.html
{% extends 'base.html' %}
{% block title%} <title>Lista de Arvores</title> {% endblock %}
{% load static %}
{% block content %}

<div class="container">
  <div class="text-center">
    <img  class="img-fluid" width="400px" style="margin-bottom: 30px; border-radius: 20px;"  src="{% static 'img/home/trees.jpg' %}" alt="home-img">
  </div>
  
  <div class="section-title">
    <h2>Lista de Arvores</h2>
    <p class="sub-title">Arvores plantadas pelo seu Usuario em todas as contas que ele faz parte </p>
  </div>
  
  
  {%if page_obj %}
  <div class="pagination">
    {% include "paginate.html" %}
  </div>

  <div>
    <p>Itens {{count}} </p>
    <hr>
    
  </div>

    <div class="list-group">
      {% for tree in page_obj %}
      <div class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
        
        <a href="{% url 'tree_detail' tree.id %}" class="d-flex w-100  list-group-item-action">
          <div>
            <h5 class="mb-1">{{tree.plant.name}}</h5>
            <p style="font-weight: 600;" class="">
              {{tree.plant.scientific_name}}
            </p>
            <p style="font-weight: 600;" class="">
              Usuario: {{tree.user | upper}}
            </p>
            <p style="font-weight: 600;" class="">
              Cadastrada em: {{tree.planted_at}}
            </p>

          </div>
        </a>

      </div>
      {% endfor %}
    </div>
  {% else %}
  <div class="pagination">
    {% include "paginate.html" %}
  </div>

  <div>
    <p>Itens {{count}} </p>
  </div>
  <hr>
  <p style="margin-bottom: 70px;" class="text-center">Ninguém plantou arvores nessa conta. <a style="font-weight: 700;"  href="{% url 'add_tree' %}">Clique aqui</a> pra começar a plantar. </p>
  {% endif%}  
</div>

{% endblock %}

trees_everywhere/core/templates/edit_profile.html
{% extends 'base.html' %}
{% block title %} <title>Editar Usuarios</title> {% endblock %}
{% block content %}

<style>
    .smal-erros{
        color: red;
        font-size: 0.875rem;
    }
</style>

<div style="margin-top: 70px;" class="container">
  <div class="row justify-content-center">
      <div class="col-md-6">
          <div class="card mt-5">
              <div class="card-header text-center">
                  <h4>Editar</h4>
              </div>
              <div class="card-body">
                <form method="post" action="{% url 'edit_profile' user.id %}">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    <div class="form-group">
                        <label for="id_username">Username:</label>
                        {{ form.username }}
                        <div class="smal-erros">
                            {{ form.username.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_first_name">Nome:</label>
                        {{ form.first_name }}
                        <div class="smal-erros">
                            {{ form.first_name.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_email">Email:</label>
                        {{ form.email }}
                        <div class="smal-erros">
                            {{ form.email.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_bio">Sobre:</label>
                        {{ form.bio }}
                        <div class="smal-erros">
                            {{ form.bio.errors }}
                        </div>
                    </div>
                    <div class="form-group ">
                        <label for="id_bio">Contas:</label>
                        {{ form.accounts }}
                        <div class="smal-erros">
                            {{ form.accounts.errors }}
                        </div>
                    </div>
                    <button id="id_register" type="submit" class="btns-all">Salvar</button>
                </form>
            </div>
          </div>
      </div>
  </div>
</div>

<script>
    $("#id_accounts").select2({
        allowClear: true, 
        placeholder: 'Selecione uma Conta',
        width: '100%',
    })
    
</script>

{% endblock %}